"use client";

import { useEffect, useState } from "react";

const loadJsonValue = async (value) => {
  if (typeof value === "string" && value.endsWith(".json")) {
    const response = await fetch(`/api/media/${value}`);
    if (response.ok) return response.json();
  }
  return value;
};

const Stat = ({ label, value }) => (
  <div className="rounded-xl border border-teal-100 bg-white p-3 shadow-sm">
    <div className="text-[11px] font-semibold uppercase tracking-wider text-teal-600">{label}</div>
    <div className="mt-1 text-2xl font-black text-slate-950">{value ?? 0}</div>
  </div>
);

const PluginStatsCard = ({ row }) => {
  const [stats, setStats] = useState(row?.value ?? {});

  useEffect(() => {
    let active = true;

    loadJsonValue(row?.value)
      .then((data) => {
        if (active) setStats(data || {});
      })
      .catch(() => {
        if (active) setStats({ error: "Could not load stats" });
      });

    return () => {
      active = false;
    };
  }, [row?.value]);

  return (
    <div className="w-full max-w-xl rounded-2xl border border-teal-200 bg-gradient-to-br from-teal-50 to-white p-4 shadow-sm">
      <div className="mb-4 flex items-center justify-between gap-4">
        <div>
          <h3 className="text-sm font-black uppercase tracking-wide text-teal-950">Text Statistics</h3>
          <p className="text-xs text-teal-700/80">Generated by the mockup plugin renderer.</p>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-3">
        <Stat label="Characters" value={stats?.characters} />
        <Stat label="Words" value={stats?.words} />
        <Stat label="Lines" value={stats?.lines} />
      </div>

      {stats?.preview && (
        <div className="mt-3 rounded-xl border border-teal-100 bg-white p-3 text-sm leading-6 text-slate-700">
          <div className="mb-1 text-[11px] font-semibold uppercase tracking-wider text-teal-600">Preview</div>
          {stats.preview}
        </div>
      )}

      {stats?.error && <div className="mt-3 text-sm font-medium text-red-600">{stats.error}</div>}
    </div>
  );
};

export default PluginStatsCard;
